import type { CastMember } from '../_types';

export const coworkManufacturingCast: CastMember[] = [
  {
    id: 'me',
    initial: '나',
    color: '#5B3FE4',
    role: 'br',
    label: '나회사 담당자',
    shortLabel: '담당자',
    org: '영업지원팀',
  },
  {
    id: 'admin',
    initial: '이',
    color: '#16172A',
    role: 'admin',
    label: '이윤 팀장',
    shortLabel: '관리자',
    org: '영업지원팀',
  },
  {
    id: 'kim',
    initial: '영',
    color: '#E67E22',
    role: 'guest',
    label: '이영업 대리',
    shortLabel: '이영업',
    org: '○○산업',
  },
  {
    id: 'park',
    initial: '열',
    color: '#D4537E',
    role: 'guest',
    label: '박열정 과장',
    shortLabel: '박열정',
    org: '○○산업',
  },
  {
    id: 'jeon',
    initial: '전',
    color: '#27AE60',
    role: 'guest',
    label: '△△전선 담당자',
    shortLabel: '△△전선',
    org: '△△전선',
  },
  {
    id: 'choi',
    initial: '최',
    color: '#27AE60',
    role: 'guest',
    label: '최구매 차장',
    shortLabel: '최구매',
    org: '△△전선',
  },
  {
    id: 'us',
    initial: 'U',
    color: '#075E54',
    role: 'other',
    label: 'US Buyer',
    shortLabel: 'US Buyer',
    org: 'Chicago',
  },
  {
    id: 'hd',
    initial: '华',
    color: '#2C2C2C',
    role: 'other',
    label: '华东化工',
    shortLabel: '华东化工',
    org: 'Shanghai',
  },
];
